# language: node_js
# node_js:
#   - '5.8.0'

git:
  depth: 3

branches:
  only:
    - master

env:
  - CXX=g++-4.8
  - NODE_VERSION='5.8.0'
  - TEST_RUN=true

matrix:
  include:
    - os: linux
      env:
        - NODE_VERSION=5.8.0
        - BUILD_OS_NAME=linux
    - os: osx
      env:
        - NODE_VERSION=5.8.0
        - BUILD_OS_NAME=darwin

script: ./script/travis-build.sh

after_success:
  - npm run coveralls
  - npm run codeclimate

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
