language: node_js
node_js:
  - "5.9.1"
branches:
  only:
    - master

compiler: clang

matrix:
   include:
    - os: linux
      env: NODE_VERSION=5.9.1
    - os: osx
      env: NODE_VERSION=5.9.1

script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
