language: node_js
node_js:
  - "5.9.1"

branches:
  only:
    - master

install:
  - rm -rf node_modules
  - npm install -g node-gyp
  - HOME=~/.electron-gyp node-gyp rebuild --target=0.37.3 --arch=x64 --dist-url=https://atom.io/download/atom-shell
  - npm install



script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
