language: node_js
node_js:
  - "5.9.0"

branches:
  only:
    - master

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
# install:
#   - rm -rf node_modules
#   - npm install -g node-gyp
#   - npm install -g electron-rebuild
#   - npm install && ./node_modules/.bin/electron-rebuild
matrix:
  include:
    - os: linux
      env: NODE_VERSION=5.9.0
    - os: osx
      env: NODE_VERSION=5.9.0


script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - build-essential
      - xvfb
