language: node_js
node_js:
  - "5.9.1"

branches:
  only:
    - master

install:
  - npm install -g node-gyp
  - npm install --save-dev electron-rebuild
  - npm install && ./node_modules/.bin/electron-rebuild



script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
