# language: node_js
# node_js:
#   - '5.8.0'

git:
  depth: 3

branches:
  only:
    - master

# env:
#   - NODE_VERSION='5.8.0'

# matrix:
#   include:
#     - os: linux
#       env:
#         - NODE_VERSION=5.8.0
#         - BUILD_OS_NAME=linux
#     - os: osx
#       env:
#         - NODE_VERSION=5.8.0
#         - BUILD_OS_NAME=darwin

before_script:
 - chmod +x ./script/travis-build.sh
 - export NODE_VERSION=5.8.0

script: ./script/travis-build.sh

after_success:
  # - npm test
  - npm run coveralls
  - npm run codeclimate

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
