language: node_js
node_js:
  - "5.9.1"

branches:
  only:
    - master

before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --set gcc /usr/bin/gcc-5

# install:
#   - rm -rf node_modules
#   - npm install -g node-gyp
#   - npm install -g electron-rebuild
#   - npm install && ./node_modules/.bin/electron-rebuild



script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - xvfb
