language: node_js
node_js:
  - "5.9.1"

branches:
  only:
    - master

# install:
#   - rm -rf node_modules
#   - npm install -g node-gyp
#   - npm install -g electron-rebuild
#   - npm install && ./node_modules/.bin/electron-rebuild



script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
