git:
  depth: 10

branches:
  only:
    - master

script:
  - npm test

env:
  global:

compiler: clang

matrix:
  include:
    - os: linux
      env: NODE_VERSION=5.3
    - os: osx
      env: NODE_VERSION=5.3

sudo: false

install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

script: script/cibuild

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
