language: node_js
node_js:
  - "5.8.0"
branches:
  only:
    - master

script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
