language: node_js
node_js:
  - '5.8.0'

branches:
  only:
    - master


install:
  - echo $CC
  - echo $CXX
  - clang --version
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION

install:
#   - export DISPLAY=':99.0'
#   - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - CXX=g++-4.8
  - npm install -g node-gyp
  - npm install --no-optional
  # - npm install -g codeclimate-test-reporter
  # - set HOME=~/.electron-gyp && node-gyp rebuild --target=$npm_package_devDependencies_electron_prebuilt --arch=x64 --dist-url=https://atom.io/download/atom-shell

# after_script:
#   - codeclimate-test-reporter < ./coverage/lcov.info

matrix:
  include:
    - os: linux
      env: NODE_VERSION=5.8.0
    - os: osx
      env: NODE_VERSION=5.8.0

before_script:
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
  export DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start;
  fi

script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
