language: node_js
node_js:
  - "5.9.1"
branches:
  only:
    - master
install:
  - npm install --no-bin-links
  
script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
